collectd:

  consumer:
    bootstrap.servers: <kafka_server_address>:9092
    group.id: collectd_extractor
    auto.offset.reset: earliest

  producer:
    bootstrap.servers: <kafka_server_address>:9092
    queue.buffering.max.messages: 500000
    queue.buffering.max.ms: 1000
    batch.num.messages: 100

  mesurement_filters_enable: True
  mesurement_filters:
    # format: {plugin}___{type}___{type_instance}
    - memory___memory___free
    - virt___memory___unused
    - virt___percent___virt_cpu_total
