collectd:
  consumer:
    bootstrap.servers: <kafka_server_address>:9092
    group.id: collectd_extractor
    auto.offset.reset: earliest

  producer:
    bootstrap.servers: <kafka_server_address>:9092
    queue.buffering.max.messages: 500000
    queue.buffering.max.ms: 1000
    batch.num.messages: 100
    api.version.request: True

  measurement_maps:
    memory___memory___free: memory_free
    cpu___percent___active: cpu_usage
    virt___memory___unused: memory_free
    virt___percent___virt_cpu_total: cpu_usage
    ping___ping___<compute_ip_address>: ping_NI-Compute-compute
    ping___ping___<controller_ip_address>: ping_NI-Compute-controller
    ping___ping___<kafka_server_address>: ping_NI-Compute-kafka
    interface___if_octets___: if_octets
    interface___if_packets___: if_packets
    interface___if_dropped___: if_dropped
